### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by zertyz** [ademakov/Evenk#3]
Thanks for sharing your work.

Could you please provide documentation on how to build?

**Comment by ademakov** [comment]
The library itself is header-only, so to using it is possibly just by copying the header files wherever you like. Building is only required for tests. It is done with standard autotools utilities. It is required to have automake and autoconf installed on your system. And of course make and gcc or clang.  As soon as you have them just run these commands:

> ./bootstrap
> ./configure
> make

**Comment by zertyz** [comment]
thanks. maybe it would be a good idea to put those into the main README.md?

**Comment by ademakov** [comment]
Just did it. Thanks for the idea.
